In [88]:
import pandas as pd

#Cleaning data

df = pd.read_csv(r"C:\Users\admin\Downloads\marketing_campaign_data_messy.csv")
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [89]:
# Header Cleaning

print(df.columns.tolist())
print("Fix Applied!")
df.columns = df.columns.str.strip().str.lower().str.replace(' ', "_") # -- to make it in lower case and remove extra space

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']
Fix Applied!

In [90]:
# Type Conversion and Currency Cleaning

messy_currency = df['spend'].astype(str).str.contains(r'\$')
print(df.loc[messy_currency,['campaign_id', 'spend']].head(3))

df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]','', regex=True)
df['spend'] = pd.to_numeric(df['spend'])
print("Fix Applied!")

print(df.loc[messy_currency,['campaign_id', 'spend']].head(3))

   campaign_id     spend
0    CMP-00001   $102.82
21   CMP-00022   $2428.4
22   CMP-00023  $4726.22
Fix Applied!
   campaign_id    spend
0    CMP-00001   102.82
21   CMP-00022  2428.40
22   CMP-00023  4726.22

In [91]:
# Cleaning the typographical errors in Channel

print(df['channel'].unique())

clean_map = {
    'Facebok' : 'Facebook',
    'Tik_Tok' : 'Tiktok',
    'E-mail' : 'Email',
    'Insta_gram' : 'Instagram',
    'Gogle' : 'Google Ads',
    'N/A' : '-'
}

df['channel'] = df['channel'].replace(clean_map)

print("Fix Applied")

print(df['channel'].unique())

<ArrowStringArray>
[    'TikTok',   'Facebook',      'Email',  'Instagram', 'Google Ads',
     'E-mail',          nan,      'Gogle',    'Tik_Tok',    'Facebok',
 'Insta_gram']
Length: 11, dtype: str
Fix Applied
<ArrowStringArray>
['TikTok', 'Facebook', 'Email', 'Instagram', 'Google Ads', nan, 'Tiktok']
Length: 7, dtype: str

In [92]:
# Handling messy booleans

print(df['active'].unique())

clean_boo = {
    'Y': 'Yes',
    '0' : 'No',
    '1' : 'Yes',
    'True' : 'Yes',
    'False' : 'No'
}

df['active'] = df['active'].replace(clean_boo)

print("Fix Applied!")

print(df['active'].unique())

<ArrowStringArray>
['Y', '0', 'No', 'True', 'Yes', '1', 'False']
Length: 7, dtype: str
Fix Applied!
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [93]:
# Date Parsing

print(df['start_date'].dtype)
df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

print("Fix Applied!")
print(df['start_date'].dtype)

str
Fix Applied!
datetime64[us]

C:\Users\admin\AppData\Local\Temp\ipykernel_11548\1984800598.py:5: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

In [94]:
df = df.loc[:, ~df.columns.duplicated()]

In [95]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,Yes,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,No,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,Yes,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,Yes,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,No,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,No,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,Yes,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,Yes,EM

In [96]:
# Clicks vs Impression
# to be equal, it's impossible that the clicks is higher than impressions
clicks_imp = df['clicks'] > df['impressions']
print(df.loc[clicks_imp,['campaign_id', 'clicks', 'impressions']].head(3))

Empty DataFrame
Columns: [campaign_id, clicks, impressions]
Index: []

In [97]:
# Time travel

date = df['end_date'] < df['start_date']
print(df.loc[date,['campaign_id', 'start_date', 'end_date']].head(3))


df.loc[date, 'end_date'] = df.loc[date, 'start_date'] + pd.Timedelta(days=30)

print("Fix Applied!")

print(df.loc[date,['campaign_id', 'start_date', 'end_date']].head(3))

   campaign_id start_date   end_date
23   CMP-00024 2023-05-06 2023-05-01
54   CMP-00055 2023-09-01 2023-08-27
71   CMP-00072 2023-02-01 2023-01-27
Fix Applied!
   campaign_id start_date   end_date
23   CMP-00024 2023-05-06 2023-06-05
54   CMP-00055 2023-09-01 2023-10-01
71   CMP-00072 2023-02-01 2023-03-03

In [107]:
# Handling Outliers

Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + (3 * IQR)

outliers = df['spend'] > upper_limit
print(df.loc[outliers,['campaign_id', 'spend']].head(3))

print("Fix Applied")
df.loc[outliers, 'spend'] = upper_limit
print(df.loc[outliers,['campaign_id','spend']].head(3))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
Fix Applied
     campaign_id      spend
789    CMP-00790  8603.5375
1443   CMP-01444  8603.5375
1460   CMP-01461  8603.5375